import axios from 'axios';

const AGMARKNET_API = 'https://api.agmarknet.gov.in/web';

const CROP_MAPPING = {
  // CEREALS & GRAINS
  'Rice': 'Rice',
  'Wheat': 'Wheat',
  'Maize': 'Maize',
  'Corn': 'Maize',
  'Jowar': 'Sorghum',
  'Sorghum': 'Sorghum',
  'Bajra': 'Pearl Millet',
  'Pearl Millet': 'Pearl Millet',
  'Ragi': 'Finger Millet',
  'Finger Millet': 'Finger Millet',
  'Barley': 'Barley',
  'Oats': 'Oats',
  'Millets': 'Millets',
  'Kodo': 'Kodo Millet',
  'Kutki': 'Kutki',
  'Buckwheat': 'Buckwheat',

  // PULSES & LEGUMES
  'Chickpea': 'Chickpea',
  'Gram': 'Chickpea',
  'Arhar': 'Pigeon Pea',
  'Pigeon Pea': 'Pigeon Pea',
  'Tur': 'Pigeon Pea',
  'Lentil': 'Lentil',
  'Masur': 'Lentil',
  'Moong': 'Green Gram',
  'Green Gram': 'Green Gram',
  'Mung': 'Green Gram',
  'Urad': 'Black Gram',
  'Black Gram': 'Black Gram',
  'Kidney Bean': 'Kidney Bean',
  'Rajma': 'Kidney Bean',
  'Pea': 'Pea',
  'Garden Pea': 'Pea',
  'Matar': 'Pea',
  'Fenugreek': 'Fenugreek',
  'Methi': 'Fenugreek',
  'Horse Gram': 'Horse Gram',
  'Moth': 'Moth Bean',
  'Cowpea': 'Cowpea',
  'Lobia': 'Cowpea',
  'Field Bean': 'Field Bean',
  'Broad Bean': 'Broad Bean',

  // OIL SEEDS
  'Groundnut': 'Groundnut',
  'Peanut': 'Groundnut',
  'Mustard': 'Mustard',
  'Rapeseed': 'Rapeseed',
  'Sunflower': 'Sunflower',
  'Soybean': 'Soybean',
  'Coconut': 'Coconut',
  'Coconut Oil': 'Coconut',
  'Coconut Kernel': 'Coconut',
  'Sesame': 'Sesame',
  'Til': 'Sesame',
  'Safflower': 'Safflower',
  'Kusum': 'Kusumbha',
  'Castor': 'Castor',
  'Niger': 'Niger',
  'Canola': 'Canola',
  'Flaxseed': 'Flaxseed',
  'Linseed': 'Flaxseed',
  'Hemp': 'Hemp',
  'Neem': 'Neem Oil',

  // VEGETABLES - LEAFY
  'Spinach': 'Spinach',
  'Palak': 'Spinach',
  'Cabbage': 'Cabbage',
  'Cauliflower': 'Cauliflower',
  'Broccoli': 'Broccoli',
  'Lettuce': 'Lettuce',
  'Coriander Leaves': 'Coriander Leaves',
  'Cilantro': 'Coriander Leaves',
  'Fenugreek Leaves': 'Fenugreek Leaves',
  'Methi Leaves': 'Fenugreek Leaves',
  'Amaranth Leaves': 'Amaranth Leaves',
  'Kale': 'Kale',
  'Mint': 'Mint',
  'Pudina': 'Mint',
  'Parsley': 'Parsley',
  'Celery': 'Celery',

  // VEGETABLES - ROOT & TUBER
  'Potato': 'Potato',
  'Carrot': 'Carrot',
  'Radish': 'Radish',
  'Mooli': 'Radish',
  'Beetroot': 'Beetroot',
  'Turnip': 'Turnip',
  'Onion': 'Onion',
  'Garlic': 'Garlic',
  'Ginger': 'Ginger',
  'Turmeric': 'Turmeric',
  'Yam': 'Yam',
  'Sweet Potato': 'Sweet Potato',
  'Cassava': 'Cassava',
  'Tapioca': 'Cassava',
  'Taro': 'Taro',
  'Arbi': 'Taro',

  // VEGETABLES - FRUIT
  'Tomato': 'Tomato',
  'Brinjal': 'Brinjal',
  'Eggplant': 'Brinjal',
  'Baingan': 'Brinjal',
  'Chilli': 'Chilli',
  'Capsicum': 'Capsicum',
  'Bell Pepper': 'Capsicum',
  'Shimla Mirch': 'Capsicum',
  'Okra': 'Okra',
  'Bhindi': 'Okra',
  'Cucumber': 'Cucumber',
  'Khira': 'Cucumber',
  'Bottle Gourd': 'Bottle Gourd',
  'Lauki': 'Bottle Gourd',
  'Bitter Gourd': 'Bitter Gourd',
  'Karela': 'Bitter Gourd',
  'Ridge Gourd': 'Ridge Gourd',
  'Tinda': 'Tinda',
  'Pumpkin': 'Pumpkin',
  'Ash Gourd': 'Ash Gourd',
  'Petha': 'Ash Gourd',
  'Zucchini': 'Zucchini',
  'Cluster Bean': 'Cluster Bean',
  'Gvar': 'Cluster Bean',
  'French Bean': 'French Bean',
  'Snake Gourd': 'Snake Gourd',
  'Ivy Gourd': 'Ivy Gourd',
  'Parwal': 'Parwal',

  // FRUITS - CITRUS
  'Orange': 'Orange',
  'Santra': 'Orange',
  'Lemon': 'Lemon',
  'Nimbu': 'Lemon',
  'Lime': 'Lime',
  'Mosambi': 'Mosambi',
  'Sweet Lime': 'Mosambi',
  'Grapefruit': 'Grapefruit',
  'Grape Fruit': 'Grapefruit',
  'Pomelo': 'Pomelo',
  'Mandarin': 'Mandarin',
  'Tangerine': 'Mandarin',
  'Pomegranate': 'Pomegranate',
  'Anar': 'Pomegranate',

  // FRUITS - STONE
  'Mango': 'Mango',
  'Aam': 'Mango',
  'Peach': 'Peach',
  'Apricot': 'Apricot',
  'Plum': 'Plum',
  'Aloobukhara': 'Plum',
  'Cherry': 'Cherry',
  'Chikhalias': 'Cherry',
  'Nectarine': 'Nectarine',
  'Litchi': 'Litchi',
  'Lychee': 'Litchi',
  'Longan': 'Longan',
  'Ber': 'Ber',
  'Jujube': 'Ber',

  // FRUITS - BERRY
  'Banana': 'Banana',
  'Kela': 'Banana',
  'Strawberry': 'Strawberry',
  'Blueberry': 'Blueberry',
  'Raspberries': 'Raspberries',
  'Mulberry': 'Mulberry',
  'Black Mulberry': 'Mulberry',
  'Blackberry': 'Blackberry',
  'Gooseberry': 'Gooseberry',
  'Amla': 'Gooseberry',
  'Indian Gooseberry': 'Gooseberry',
  'Elderberry': 'Elderberry',
  'Boysenberry': 'Boysenberry',

  // FRUITS - OTHER
  'Apple': 'Apple',
  'Seb': 'Apple',
  'Pear': 'Pear',
  'Nashpati': 'Pear',
  'Guava': 'Guava',
  'Amrud': 'Guava',
  'Papaya': 'Papaya',
  'Pawpaw': 'Papaya',
  'Pineapple': 'Pineapple',
  'Ananas': 'Pineapple',
  'Coconut': 'Coconut',
  'Watermelon': 'Watermelon',
  'Tarbooj': 'Watermelon',
  'Muskmelon': 'Muskmelon',
  'Kharbuza': 'Muskmelon',
  'Cantaloupe': 'Muskmelon',
  'Dragon Fruit': 'Dragon Fruit',
  'Kiwi': 'Kiwi',
  'Kiwifruit': 'Kiwi',
  'Passion Fruit': 'Passion Fruit',
  'Custard Apple': 'Custard Apple',
  'Sitaphal': 'Custard Apple',
  'Soursop': 'Soursop',
  'Graviola': 'Soursop',
  'Avocado': 'Avocado',
  'Jackfruit': 'Jackfruit',
  'Kathal': 'Jackfruit',
  'Breadfruit': 'Breadfruit',
  'Fig': 'Fig',
  'Anjeer': 'Fig',

  // SPICES & CONDIMENTS
  'Turmeric': 'Turmeric',
  'Haldi': 'Turmeric',
  'Coriander': 'Coriander',
  'Dhania': 'Coriander',
  'Cumin': 'Cumin',
  'Jeera': 'Cumin',
  'Chilli': 'Chilli',
  'Mirch': 'Chilli',
  'Fenugreek': 'Fenugreek',
  'Methi': 'Fenugreek',
  'Caraway': 'Caraway',
  'Ajwain': 'Caraway',
  'Fennel': 'Fennel',
  'Saunf': 'Fennel',
  'Anise': 'Anise',
  'Asafoetida': 'Asafoetida',
  'Hing': 'Asafoetida',
  'Mustard Seed': 'Mustard Seed',
  'Rai': 'Mustard Seed',
  'Nigella': 'Nigella',
  'Kalonji': 'Nigella',
  'Black Cumin': 'Nigella',
  'Fenugreek Seed': 'Fenugreek',
  'Clove': 'Clove',
  'Laung': 'Clove',
  'Cinnamon': 'Cinnamon',
  'Daalchini': 'Cinnamon',
  'Nutmeg': 'Nutmeg',
  'Jaiphal': 'Nutmeg',
  'Cardamom': 'Cardamom',
  'Elaichi': 'Cardamom',
  'Black Cardamom': 'Black Cardamom',
  'Mace': 'Mace',
  'Javitri': 'Mace',
  'Pepper': 'Pepper',
  'Kali Mirch': 'Pepper',
  'Black Pepper': 'Pepper',
  'White Pepper': 'Pepper',
  'Clove': 'Clove',
  'Star Anise': 'Star Anise',
  'Bay Leaf': 'Bay Leaf',
  'Tej Patta': 'Bay Leaf',
  'Saffron': 'Saffron',
  'Kesar': 'Saffron',

  // CASH CROPS
  'Cotton': 'Cotton',
  'Kapas': 'Cotton',
  'Sugarcane': 'Sugarcane',
  'Ganna': 'Sugarcane',
  'Tobacco': 'Tobacco',
  'Dhumbakhu': 'Tobacco',
  'Tea': 'Tea',
  'Chai Patti': 'Tea',
  'Coffee': 'Coffee',
  'Kopi': 'Coffee',
  'Indigo': 'Indigo',
  'Neel': 'Indigo',
  'Jute': 'Jute',
  'Pat': 'Jute',
  'Hemp': 'Hemp',
  'Sisal': 'Sisal',
  'Rubber': 'Rubber',
  'Lac': 'Lac',
  'Shellac': 'Shellac',

  // FLOWERS & ORNAMENTAL
  'Marigold': 'Marigold',
  'Genda': 'Marigold',
  'Jasmine': 'Jasmine',
  'Chameli': 'Jasmine',
  'Rose': 'Rose',
  'Gulab': 'Rose',
  'Chrysanthemum': 'Chrysanthemum',
  'Guldaudi': 'Chrysanthemum',
  'Sunflower': 'Sunflower',
  'Surajmukhi': 'Sunflower',
  'Hibiscus': 'Hibiscus',
  'Gul-e-Surkh': 'Hibiscus',
  'Bougainvillea': 'Bougainvillea',
  'Lotus': 'Lotus',
  'Kamal': 'Lotus',
  'Water Lily': 'Water Lily',
  'Nilofar': 'Water Lily',
  'Orchid': 'Orchid',
  'Dahlia': 'Dahlia',
  'Cosmos': 'Cosmos',
  'Zinnia': 'Zinnia',
  'Gladiolus': 'Gladiolus',

  // FORAGE & FODDER
  'Lucerne': 'Lucerne',
  'Alfalfa': 'Lucerne',
  'Berseem': 'Berseem',
  'Egyptian Clover': 'Berseem',
  'Cowpea Fodder': 'Cowpea',
  'Oat Fodder': 'Oats',
  'Maize Fodder': 'Maize',
  'Sorghum Fodder': 'Sorghum',
  'Jowar Fodder': 'Sorghum',
  'Grass': 'Grass',
  'Pasture': 'Pasture',

  // MEDICINAL & AROMATIC
  'Basil': 'Basil',
  'Tulsi': 'Basil',
  'Holy Basil': 'Basil',
  'Mint': 'Mint',
  'Pudina': 'Mint',
  'Lemongrass': 'Lemongrass',
  'Citronella': 'Citronella',
  'Lavender': 'Lavender',
  'Thyme': 'Thyme',
  'Oregano': 'Oregano',
  'Marjoram': 'Marjoram',
  'Sage': 'Sage',
  'Rosemary': 'Rosemary',
  'Dill': 'Dill',
  'Soya': 'Soybean',
  'Ashwagandha': 'Ashwagandha',
  'Sarpagandha': 'Sarpagandha',
  'Brahmi': 'Brahmi',
  'Bacopa': 'Brahmi',
  'Hibiscus': 'Hibiscus',
  'Aloe Vera': 'Aloe Vera',
  'Musabbar': 'Aloe Vera',
  'Neem': 'Neem',
  'Shivlingi': 'Shivlingi',
  'Ginseng': 'Ginseng',
  'Panax': 'Ginseng',

  // NUTS
  'Cashew': 'Cashew',
  'Kaju': 'Cashew',
  'Almond': 'Almond',
  'Badam': 'Almond',
  'Walnut': 'Walnut',
  'Akhrot': 'Walnut',
  'Pistachio': 'Pistachio',
  'Pista': 'Pistachio',
  'Pine Nut': 'Pine Nut',
  'Hazelnut': 'Hazelnut',
  'Macadamia': 'Macadamia',
  'Chestnut': 'Chestnut',
  'Pecan': 'Pecan',

  // MUSHROOMS
  'Button Mushroom': 'Button Mushroom',
  'Oyster Mushroom': 'Oyster Mushroom',
  'Shiitake': 'Shiitake',
  'Morel': 'Morel',
  'Truffle': 'Truffle',

  // MISCELLANEOUS
  'Sugarbeet': 'Sugarbeet',
  'Sabudam Shakkar': 'Sugarbeet',
  'Hops': 'Hops',
  'Lavender': 'Lavender',
  'Honey': 'Honey',
  'Sericulture': 'Silk',
  'Silk': 'Silk',
  'Apiculture': 'Honey',
  'Vermicompost': 'Vermicompost',
  'Seaweed': 'Seaweed',
  'Seagrass': 'Seagrass',
  'Bamboo': 'Bamboo',
  'Bambusa': 'Bamboo',
  'Rattan': 'Rattan',
  'Willow': 'Willow',
  'Eucalyptus': 'Eucalyptus',
  'Teak': 'Teak',
  'Shisham': 'Teak',
  'Deodar': 'Deodar',
  'Chir Pine': 'Pine',
  'Sal': 'Sal',

  // TREE CROPS
  'Date Palm': 'Date Palm',
  'Khajoor': 'Date Palm',
  'Arecanut': 'Arecanut',
  'Betel Nut': 'Arecanut',
  'Supari': 'Arecanut',
  'Black Pepper Vine': 'Black Pepper',
  'Vanilla': 'Vanilla',
  'Cacao': 'Cacao',
  'Cocoa': 'Cacao',
  'Cocum': 'Cocum',
  'Kokam': 'Cocum',

  // AQUATIC CROPS
  'Seaweed': 'Seaweed',
  'Kelp': 'Kelp',
  'Pond Weed': 'Aquatic Plants',
  'Water Hyacinth': 'Water Hyacinth',
  'Lotus Root': 'Lotus',
};

const DISTRICT_TO_MARKET = {
  // Andaman and Nicobar Islands
  'North and Middle Andaman': { state: 'Andaman and Nicobar Islands', market: 'Port Blair' },
  'South Andaman': { state: 'Andaman and Nicobar Islands', market: 'Port Blair' },
  'Nicobar': { state: 'Andaman and Nicobar Islands', market: 'Port Blair' },

  // Andhra Pradesh
  'Alluri Sitharama Raju': { state: 'Andhra Pradesh', market: 'Vizag' },
  'Anakapalli': { state: 'Andhra Pradesh', market: 'Vizag' },
  'Anantapur': { state: 'Andhra Pradesh', market: 'Anantapur' },
  'Annamayya': { state: 'Andhra Pradesh', market: 'Tirupati' },
  'Bapatla': { state: 'Andhra Pradesh', market: 'Nellore' },
  'Chittoor': { state: 'Andhra Pradesh', market: 'Chittoor' },
  'Dr. B.R. Ambedkar Konaseema': { state: 'Andhra Pradesh', market: 'Vijayawada' },
  'Eluru': { state: 'Andhra Pradesh', market: 'Vijayawada' },
  'East Godavari': { state: 'Andhra Pradesh', market: 'Rajahmundry' },
  'Guntur': { state: 'Andhra Pradesh', market: 'Guntur' },
  'Kakinada': { state: 'Andhra Pradesh', market: 'Kakinada' },
  'Krishna': { state: 'Andhra Pradesh', market: 'Vijayawada' },
  'Kurnool': { state: 'Andhra Pradesh', market: 'Kurnool' },
  'NTR': { state: 'Andhra Pradesh', market: 'Vijayawada' },
  'Nandyal': { state: 'Andhra Pradesh', market: 'Anantapur' },
  'Palnadu': { state: 'Andhra Pradesh', market: 'Guntur' },
  'Parvathipuram Manyam': { state: 'Andhra Pradesh', market: 'Vizag' },
  'Prakasam': { state: 'Andhra Pradesh', market: 'Nellore' },
  'Sri Potti Sriramulu Nellore': { state: 'Andhra Pradesh', market: 'Nellore' },
  'Sri Sathya Sai': { state: 'Andhra Pradesh', market: 'Anantapur' },
  'Srikakulam': { state: 'Andhra Pradesh', market: 'Vizag' },
  'Tirupati': { state: 'Andhra Pradesh', market: 'Tirupati' },
  'Visakhapatnam': { state: 'Andhra Pradesh', market: 'Vizag' },
  'Vizianagaram': { state: 'Andhra Pradesh', market: 'Vizag' },
  'West Godavari': { state: 'Andhra Pradesh', market: 'Vijayawada' },
  'YSR Kadapa': { state: 'Andhra Pradesh', market: 'Kadapa' },

  // Arunachal Pradesh
  'Anjaw': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Changlang': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Dibang Valley': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'East Kameng': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'East Siang': { state: 'Arunachal Pradesh', market: 'Pasighat' },
  'Kra Daadi': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Kurung Kumey': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Lohit': { state: 'Arunachal Pradesh', market: 'Tezu' },
  'Lower Dibang Valley': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Lower Siang': { state: 'Arunachal Pradesh', market: 'Pasighat' },
  'Lower Subansiri': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Longding': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Namsai': { state: 'Arunachal Pradesh', market: 'Tezu' },
  'Papum Pare': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Siang': { state: 'Arunachal Pradesh', market: 'Pasighat' },
  'Tawang': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Tirap': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'Upper Siang': { state: 'Arunachal Pradesh', market: 'Pasighat' },
  'Upper Subansiri': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'West Kameng': { state: 'Arunachal Pradesh', market: 'Itanagar' },
  'West Siang': { state: 'Arunachal Pradesh', market: 'Pasighat' },

  // Assam
  'Baksa': { state: 'Assam', market: 'Guwahati' },
  'Barpeta': { state: 'Assam', market: 'Guwahati' },
  'Bajali': { state: 'Assam', market: 'Guwahati' },
  'Biswanath': { state: 'Assam', market: 'Tezpur' },
  'Bongaigaon': { state: 'Assam', market: 'Guwahati' },
  'Cachar': { state: 'Assam', market: 'Silchar' },
  'Charaideo': { state: 'Assam', market: 'Guwahati' },
  'Chirang': { state: 'Assam', market: 'Guwahati' },
  'Darrang': { state: 'Assam', market: 'Guwahati' },
  'Dhemaji': { state: 'Assam', market: 'Tezpur' },
  'Dhubri': { state: 'Assam', market: 'Guwahati' },
  'Dibrugarh': { state: 'Assam', market: 'Dibrugarh' },
  'Dima Hasao': { state: 'Assam', market: 'Silchar' },
  'Goalpara': { state: 'Assam', market: 'Guwahati' },
  'Golaghat': { state: 'Assam', market: 'Guwahati' },
  'Hailakandi': { state: 'Assam', market: 'Silchar' },
  'Hojai': { state: 'Assam', market: 'Guwahati' },
  'Jorhat': { state: 'Assam', market: 'Jorhat' },
  'Kamrup': { state: 'Assam', market: 'Guwahati' },
  'Kamrup Metropolitan': { state: 'Assam', market: 'Guwahati' },
  'Karbi Anglong': { state: 'Assam', market: 'Guwahati' },
  'Karimganj': { state: 'Assam', market: 'Silchar' },
  'Kokrajhar': { state: 'Assam', market: 'Guwahati' },
  'Lakhimpur': { state: 'Assam', market: 'Dibrugarh' },
  'Majuli': { state: 'Assam', market: 'Jorhat' },
  'Morigaon': { state: 'Assam', market: 'Guwahati' },
  'Nagaon': { state: 'Assam', market: 'Guwahati' },
  'Nalbari': { state: 'Assam', market: 'Guwahati' },
  'Sivasagar': { state: 'Assam', market: 'Jorhat' },
  'Sonitpur': { state: 'Assam', market: 'Tezpur' },
  'South Salmara Mankachar': { state: 'Assam', market: 'Guwahati' },
  'Tamulpur': { state: 'Assam', market: 'Guwahati' },
  'Tinsukia': { state: 'Assam', market: 'Dibrugarh' },
  'Udalguri': { state: 'Assam', market: 'Guwahati' },
  'West Karbi Anglong': { state: 'Assam', market: 'Guwahati' },

  // Bihar
  'Araria': { state: 'Bihar', market: 'Araria' },
  'Arwal': { state: 'Bihar', market: 'Gaya' },
  'Aurangabad': { state: 'Bihar', market: 'Gaya' },
  'Banka': { state: 'Bihar', market: 'Bhagalpur' },
  'Begusarai': { state: 'Bihar', market: 'Darbhanga' },
  'Bhagalpur': { state: 'Bihar', market: 'Bhagalpur' },
  'Bhojpur': { state: 'Bihar', market: 'Patna' },
  'Buxar': { state: 'Bihar', market: 'Patna' },
  'Darbhanga': { state: 'Bihar', market: 'Darbhanga' },
  'East Champaran': { state: 'Bihar', market: 'Motihari' },
  'Gaya': { state: 'Bihar', market: 'Gaya' },
  'Gopalganj': { state: 'Bihar', market: 'Siwan' },
  'Jamui': { state: 'Bihar', market: 'Bhagalpur' },
  'Jehanabad': { state: 'Bihar', market: 'Gaya' },
  'Kaimur': { state: 'Bihar', market: 'Bhabhua' },
  'Katihar': { state: 'Bihar', market: 'Katihar' },
  'Khagaria': { state: 'Bihar', market: 'Darbhanga' },
  'Kishanganj': { state: 'Bihar', market: 'Katihar' },
  'Lakhisarai': { state: 'Bihar', market: 'Bhagalpur' },
  'Madhepura': { state: 'Bihar', market: 'Katihar' },
  'Madhubani': { state: 'Bihar', market: 'Darbhanga' },
  'Munger': { state: 'Bihar', market: 'Bhagalpur' },
  'Muzaffarpur': { state: 'Bihar', market: 'Muzaffarpur' },
  'Nalanda': { state: 'Bihar', market: 'Gaya' },
  'Nawada': { state: 'Bihar', market: 'Gaya' },
  'Patna': { state: 'Bihar', market: 'Patna' },
  'Purnia': { state: 'Bihar', market: 'Katihar' },
  'Rohtas': { state: 'Bihar', market: 'Bhabhua' },
  'Saharsa': { state: 'Bihar', market: 'Katihar' },
  'Samastipur': { state: 'Bihar', market: 'Darbhanga' },
  'Saran': { state: 'Bihar', market: 'Chhapra' },
  'Sheikhpura': { state: 'Bihar', market: 'Gaya' },
  'Sheohar': { state: 'Bihar', market: 'Muzaffarpur' },
  'Sitamarhi': { state: 'Bihar', market: 'Muzaffarpur' },
  'Siwan': { state: 'Bihar', market: 'Siwan' },
  'Supaul': { state: 'Bihar', market: 'Katihar' },
  'Vaishali': { state: 'Bihar', market: 'Hajipur' },
  'West Champaran': { state: 'Bihar', market: 'Motihari' },

  // Chandigarh
  'Chandigarh': { state: 'Chandigarh', market: 'Chandigarh' },

  // Chhattisgarh
  'Balod': { state: 'Chhattisgarh', market: 'Raipur' },
  'Baloda Bazar': { state: 'Chhattisgarh', market: 'Raipur' },
  'Balrampur': { state: 'Chhattisgarh', market: 'Raipur' },
  'Bastar': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Bemetara': { state: 'Chhattisgarh', market: 'Raipur' },
  'Bijapur': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Bilaspur': { state: 'Chhattisgarh', market: 'Bilaspur' },
  'Dantewada': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Dhamtari': { state: 'Chhattisgarh', market: 'Raipur' },
  'Durg': { state: 'Chhattisgarh', market: 'Durg' },
  'Gariaband': { state: 'Chhattisgarh', market: 'Raipur' },
  'Janjgir-Champa': { state: 'Chhattisgarh', market: 'Raipur' },
  'Jashpur': { state: 'Chhattisgarh', market: 'Bilaspur' },
  'Kabirdham': { state: 'Chhattisgarh', market: 'Bilaspur' },
  'Kanker': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Kondagaon': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Korba': { state: 'Chhattisgarh', market: 'Korba' },
  'Korea': { state: 'Chhattisgarh', market: 'Manendragarh' },
  'Mahasamund': { state: 'Chhattisgarh', market: 'Raipur' },
  'Mungeli': { state: 'Chhattisgarh', market: 'Bilaspur' },
  'Narayanpur': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Raigarh': { state: 'Chhattisgarh', market: 'Raigarh' },
  'Raipur': { state: 'Chhattisgarh', market: 'Raipur' },
  'Rajnandgaon': { state: 'Chhattisgarh', market: 'Durg' },
  'Sukma': { state: 'Chhattisgarh', market: 'Jagdalpur' },
  'Surajpur': { state: 'Chhattisgarh', market: 'Korba' },
  'Surguja': { state: 'Chhattisgarh', market: 'Ambikapur' },

  // Dadra and Nagar Haveli
  'Dadra': { state: 'Dadra and Nagar Haveli', market: 'Silvassa' },
  'Nagar Haveli': { state: 'Dadra and Nagar Haveli', market: 'Silvassa' },

  // Daman and Diu
  'Daman': { state: 'Daman and Diu', market: 'Daman' },
  'Diu': { state: 'Daman and Diu', market: 'Diu' },

  // Delhi
  'Central Delhi': { state: 'Delhi', market: 'Delhi' },
  'East Delhi': { state: 'Delhi', market: 'Delhi' },
  'New Delhi': { state: 'Delhi', market: 'Delhi' },
  'North Delhi': { state: 'Delhi', market: 'Delhi' },
  'North East Delhi': { state: 'Delhi', market: 'Delhi' },
  'North West Delhi': { state: 'Delhi', market: 'Delhi' },
  'Shahdara': { state: 'Delhi', market: 'Delhi' },
  'South Delhi': { state: 'Delhi', market: 'Delhi' },
  'South East Delhi': { state: 'Delhi', market: 'Delhi' },
  'South West Delhi': { state: 'Delhi', market: 'Delhi' },
  'West Delhi': { state: 'Delhi', market: 'Delhi' },

  // Goa
  'North Goa': { state: 'Goa', market: 'Panaji' },
  'South Goa': { state: 'Goa', market: 'Margao' },

  // Gujarat
  'Ahmedabad': { state: 'Gujarat', market: 'Ahmedabad' },
  'Amreli': { state: 'Gujarat', market: 'Rajkot' },
  'Anand': { state: 'Gujarat', market: 'Anand' },
  'Aravalli': { state: 'Gujarat', market: 'Modasa' },
  'Banaskantha': { state: 'Gujarat', market: 'Palanpur' },
  'Bharuch': { state: 'Gujarat', market: 'Bharuch' },
  'Bhavnagar': { state: 'Gujarat', market: 'Bhavnagar' },
  'Botad': { state: 'Gujarat', market: 'Rajkot' },
  'Chhota Udaipur': { state: 'Gujarat', market: 'Vadodara' },
  'Dahod': { state: 'Gujarat', market: 'Indore' },
  'Dang': { state: 'Gujarat', market: 'Vadodara' },
  'Devbhoomi Dwarka': { state: 'Gujarat', market: 'Jamnagar' },
  'Gandhinagar': { state: 'Gujarat', market: 'Ahmedabad' },
  'Gir Somnath': { state: 'Gujarat', market: 'Junagadh' },
  'Jamnagar': { state: 'Gujarat', market: 'Jamnagar' },
  'Junagadh': { state: 'Gujarat', market: 'Junagadh' },
  'Kheda': { state: 'Gujarat', market: 'Anand' },
  'Kutch': { state: 'Gujarat', market: 'Bhuj' },
  'Mahisagar': { state: 'Gujarat', market: 'Vadodara' },
  'Mehsana': { state: 'Gujarat', market: 'Mehsana' },
  'Morbi': { state: 'Gujarat', market: 'Rajkot' },
  'Narmada': { state: 'Gujarat', market: 'Bharuch' },
  'Navsari': { state: 'Gujarat', market: 'Surat' },
  'Panchmahal': { state: 'Gujarat', market: 'Vadodara' },
  'Patan': { state: 'Gujarat', market: 'Mehsana' },
  'Porbandar': { state: 'Gujarat', market: 'Porbandar' },
  'Rajkot': { state: 'Gujarat', market: 'Rajkot' },
  'Sabarkantha': { state: 'Gujarat', market: 'Mehsana' },
  'Surat': { state: 'Gujarat', market: 'Surat' },
  'Surendranagar': { state: 'Gujarat', market: 'Surendranagar' },
  'Tapi': { state: 'Gujarat', market: 'Surat' },
  'Vadodara': { state: 'Gujarat', market: 'Vadodara' },
  'Valsad': { state: 'Gujarat', market: 'Valsad' },

  // Haryana
  'Ambala': { state: 'Haryana', market: 'Ambala' },
  'Bhiwani': { state: 'Haryana', market: 'Bhiwani' },
  'Charkhi Dadri': { state: 'Haryana', market: 'Rohtak' },
  'Faridabad': { state: 'Haryana', market: 'Faridabad' },
  'Fatehabad': { state: 'Haryana', market: 'Fatehabad' },
  'Gurgaon': { state: 'Haryana', market: 'Delhi' },
  'Hisar': { state: 'Haryana', market: 'Hisar' },
  'Jhajjar': { state: 'Haryana', market: 'Rohtak' },
  'Jind': { state: 'Haryana', market: 'Jind' },
  'Kaithal': { state: 'Haryana', market: 'Kaithal' },
  'Karnal': { state: 'Haryana', market: 'Karnal' },
  'Kurukshetra': { state: 'Haryana', market: 'Kurukshetra' },
  'Mahendragarh': { state: 'Haryana', market: 'Hisar' },
  'Mewat': { state: 'Haryana', market: 'Mewat' },
  'Palwal': { state: 'Haryana', market: 'Palwal' },
  'Panchkula': { state: 'Haryana', market: 'Panchkula' },
  'Panipat': { state: 'Haryana', market: 'Panipat' },
  'Rewari': { state: 'Haryana', market: 'Hisar' },
  'Rohtak': { state: 'Haryana', market: 'Rohtak' },
  'Sirsa': { state: 'Haryana', market: 'Sirsa' },
  'Sonipat': { state: 'Haryana', market: 'Sonipat' },
  'Yamunanagar': { state: 'Haryana', market: 'Yamunanagar' },

  // Himachal Pradesh
  'Bilaspur': { state: 'Himachal Pradesh', market: 'Bilaspur' },
  'Chamba': { state: 'Himachal Pradesh', market: 'Chamba' },
  'Hamirpur': { state: 'Himachal Pradesh', market: 'Hamirpur' },
  'Kangra': { state: 'Himachal Pradesh', market: 'Kangra' },
  'Kinnaur': { state: 'Himachal Pradesh', market: 'Shimla' },
  'Kullu': { state: 'Himachal Pradesh', market: 'Kullu' },
  'Lahaul and Spiti': { state: 'Himachal Pradesh', market: 'Keylong' },
  'Mandi': { state: 'Himachal Pradesh', market: 'Mandi' },
  'Shimla': { state: 'Himachal Pradesh', market: 'Shimla' },
  'Sirmaur': { state: 'Himachal Pradesh', market: 'Nahan' },
  'Solan': { state: 'Himachal Pradesh', market: 'Solan' },
  'Una': { state: 'Himachal Pradesh', market: 'Una' },

  // Jharkhand
  'Bokaro': { state: 'Jharkhand', market: 'Bokaro' },
  'Chatra': { state: 'Jharkhand', market: 'Ranchi' },
  'Deoghar': { state: 'Jharkhand', market: 'Deoghar' },
  'Dhanbad': { state: 'Jharkhand', market: 'Dhanbad' },
  'Dumka': { state: 'Jharkhand', market: 'Dumka' },
  'East Singhbhum': { state: 'Jharkhand', market: 'Jamshedpur' },
  'Garhwa': { state: 'Jharkhand', market: 'Garhwa' },
  'Giridih': { state: 'Jharkhand', market: 'Giridih' },
  'Godda': { state: 'Jharkhand', market: 'Godda' },
  'Gumla': { state: 'Jharkhand', market: 'Gumla' },
  'Hazaribagh': { state: 'Jharkhand', market: 'Hazaribagh' },
  'Jamtara': { state: 'Jharkhand', market: 'Jamtara' },
  'Khunti': { state: 'Jharkhand', market: 'Ranchi' },
  'Koderma': { state: 'Jharkhand', market: 'Koderma' },
  'Latehar': { state: 'Jharkhand', market: 'Latehar' },
  'Lohardaga': { state: 'Jharkhand', market: 'Lohardaga' },
  'Pakur': { state: 'Jharkhand', market: 'Pakur' },
  'Palamu': { state: 'Jharkhand', market: 'Daltonganj' },
  'Ramgarh': { state: 'Jharkhand', market: 'Bokaro' },
  'Ranchi': { state: 'Jharkhand', market: 'Ranchi' },
  'Sahibganj': { state: 'Jharkhand', market: 'Sahibganj' },
  'Saraikela Kharsawan': { state: 'Jharkhand', market: 'Jamshedpur' },
  'Simdega': { state: 'Jharkhand', market: 'Gumla' },
  'West Singhbhum': { state: 'Jharkhand', market: 'Jamshedpur' },

  // Jammu and Kashmir
  'Anantnag': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Bandipora': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Baramulla': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Budgam': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Doda': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Ganderbal': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Jammu': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Kathua': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Kishtwar': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Kulgam': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Kupwara': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Poonch': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Pulwama': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Rajouri': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Ramban': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Reasi': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Samba': { state: 'Jammu and Kashmir', market: 'Jammu' },
  'Shopian': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Srinagar': { state: 'Jammu and Kashmir', market: 'Srinagar' },
  'Udhampur': { state: 'Jammu and Kashmir', market: 'Jammu' },

  // Karnataka
  'Bagalkot': { state: 'Karnataka', market: 'Belgaum' },
  'Bangalore Rural': { state: 'Karnataka', market: 'Bangalore' },
  'Bangalore Urban': { state: 'Karnataka', market: 'Bangalore' },
  'Belagavi': { state: 'Karnataka', market: 'Belgaum' },
  'Ballari': { state: 'Karnataka', market: 'Ballari' },
  'Bidar': { state: 'Karnataka', market: 'Bidar' },
  'Chamarajanagar': { state: 'Karnataka', market: 'Mysuru' },
  'Chikballapur': { state: 'Karnataka', market: 'Chikballapur' },
  'Chikkamagaluru': { state: 'Karnataka', market: 'Chikkamagaluru' },
  'Chitradurga': { state: 'Karnataka', market: 'Chitradurga' },
  'Dakshina Kannada': { state: 'Karnataka', market: 'Mangalore' },
  'Davangere': { state: 'Karnataka', market: 'Davangere' },
  'Dharwad': { state: 'Karnataka', market: 'Hubballi' },
  'Gadag': { state: 'Karnataka', market: 'Gadag' },
  'Hassan': { state: 'Karnataka', market: 'Hassan' },
  'Haveri': { state: 'Karnataka', market: 'Haveri' },
  'Kalaburagi': { state: 'Karnataka', market: 'Kalaburagi' },
  'Kodagu': { state: 'Karnataka', market: 'Madikeri' },
  'Kolar': { state: 'Karnataka', market: 'Kolar' },
  'Koppal': { state: 'Karnataka', market: 'Koppal' },
  'Mandya': { state: 'Karnataka', market: 'Mandya' },
  'Mysuru': { state: 'Karnataka', market: 'Mysuru' },
  'Raichur': { state: 'Karnataka', market: 'Raichur' },
  'Ramanagara': { state: 'Karnataka', market: 'Bangalore' },
  'Shivamogga': { state: 'Karnataka', market: 'Shivamogga' },
  'Tumakuru': { state: 'Karnataka', market: 'Tumakuru' },
  'Udupi': { state: 'Karnataka', market: 'Udupi' },
  'Uttara Kannada': { state: 'Karnataka', market: 'Karwar' },
  'Vijayapura': { state: 'Karnataka', market: 'Belgaum' },
  'Yadgir': { state: 'Karnataka', market: 'Kalaburagi' },

  // Kerala
  'Alappuzha': { state: 'Kerala', market: 'Kottayam' },
  'Ernakulam': { state: 'Kerala', market: 'Ernakulam' },
  'Idukki': { state: 'Kerala', market: 'Kottayam' },
  'Kannur': { state: 'Kerala', market: 'Kannur' },
  'Kasaragod': { state: 'Kerala', market: 'Kasaragod' },
  'Kollam': { state: 'Kerala', market: 'Thiruvananthapuram' },
  'Kottayam': { state: 'Kerala', market: 'Kottayam' },
  'Kozhikode': { state: 'Kerala', market: 'Kozhikode' },
  'Malappuram': { state: 'Kerala', market: 'Kozhikode' },
  'Palakkad': { state: 'Kerala', market: 'Palakkad' },
  'Pathanamthitta': { state: 'Kerala', market: 'Kottayam' },
  'Thiruvananthapuram': { state: 'Kerala', market: 'Thiruvananthapuram' },
  'Thrissur': { state: 'Kerala', market: 'Thrissur' },
  'Wayanad': { state: 'Kerala', market: 'Kozhikode' },

  // Lakshadweep
  'Agatti': { state: 'Lakshadweep', market: 'Lakshadweep' },
  'Amini': { state: 'Lakshadweep', market: 'Lakshadweep' },
  'Andrott': { state: 'Lakshadweep', market: 'Lakshadweep' },
  'Kavaratti': { state: 'Lakshadweep', market: 'Lakshadweep' },
  'Kalapeni': { state: 'Lakshadweep', market: 'Lakshadweep' },
  'Kiltan': { state: 'Lakshadweep', market: 'Lakshadweep' },
  'Minicoy': { state: 'Lakshadweep', market: 'Lakshadweep' },

  // Ladakh
  'Kargil': { state: 'Ladakh', market: 'Leh' },
  'Leh': { state: 'Ladakh', market: 'Leh' },

  // Madhya Pradesh
  'Agar Malwa': { state: 'Madhya Pradesh', market: 'Indore' },
  'Alirajpur': { state: 'Madhya Pradesh', market: 'Indore' },
  'Anuppur': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Ashoknagar': { state: 'Madhya Pradesh', market: 'Guna' },
  'Balaghat': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Barwani': { state: 'Madhya Pradesh', market: 'Indore' },
  'Betul': { state: 'Madhya Pradesh', market: 'Indore' },
  'Bhind': { state: 'Madhya Pradesh', market: 'Gwalior' },
  'Bhopal': { state: 'Madhya Pradesh', market: 'Bhopal' },
  'Burhanpur': { state: 'Madhya Pradesh', market: 'Indore' },
  'Chhatarpur': { state: 'Madhya Pradesh', market: 'Chhatarpur' },
  'Chhindwara': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Damoh': { state: 'Madhya Pradesh', market: 'Damoh' },
  'Datia': { state: 'Madhya Pradesh', market: 'Gwalior' },
  'Dewas': { state: 'Madhya Pradesh', market: 'Indore' },
  'Dhar': { state: 'Madhya Pradesh', market: 'Indore' },
  'Dindori': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Guna': { state: 'Madhya Pradesh', market: 'Guna' },
  'Gwalior': { state: 'Madhya Pradesh', market: 'Gwalior' },
  'Harda': { state: 'Madhya Pradesh', market: 'Indore' },
  'Hoshangabad': { state: 'Madhya Pradesh', market: 'Hoshangabad' },
  'Indore': { state: 'Madhya Pradesh', market: 'Indore' },
  'Jabalpur': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Jhabua': { state: 'Madhya Pradesh', market: 'Indore' },
  'Katni': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Khandwa': { state: 'Madhya Pradesh', market: 'Indore' },
  'Khargone': { state: 'Madhya Pradesh', market: 'Indore' },
  'Mandla': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Mandsaur': { state: 'Madhya Pradesh', market: 'Indore' },
  'Morena': { state: 'Madhya Pradesh', market: 'Gwalior' },
  'Narsinghpur': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Neemuch': { state: 'Madhya Pradesh', market: 'Indore' },
  'Panna': { state: 'Madhya Pradesh', market: 'Chhatarpur' },
  'Raisen': { state: 'Madhya Pradesh', market: 'Bhopal' },
  'Rajgarh': { state: 'Madhya Pradesh', market: 'Indore' },
  'Ratlam': { state: 'Madhya Pradesh', market: 'Indore' },
  'Rewa': { state: 'Madhya Pradesh', market: 'Rewa' },
  'Sagar': { state: 'Madhya Pradesh', market: 'Sagar' },
  'Satna': { state: 'Madhya Pradesh', market: 'Satna' },
  'Sehore': { state: 'Madhya Pradesh', market: 'Bhopal' },
  'Seoni': { state: 'Madhya Pradesh', market: 'Jabalpur' },
  'Shahdol': { state: 'Madhya Pradesh', market: 'Shahdol' },
  'Shajapur': { state: 'Madhya Pradesh', market: 'Indore' },
  'Sheopur': { state: 'Madhya Pradesh', market: 'Gwalior' },
  'Shivpuri': { state: 'Madhya Pradesh', market: 'Gwalior' },
  'Sidhi': { state: 'Madhya Pradesh', market: 'Sidhi' },
  'Singrauli': { state: 'Madhya Pradesh', market: 'Singrauli' },
  'Tikamgarh': { state: 'Madhya Pradesh', market: 'Tikamgarh' },
  'Ujjain': { state: 'Madhya Pradesh', market: 'Indore' },
  'Umaria': { state: 'Madhya Pradesh', market: 'Umaria' },
  'Vidisha': { state: 'Madhya Pradesh', market: 'Bhopal' },

  // Maharashtra
  'Ahmednagar': { state: 'Maharashtra', market: 'Ahmednagar' },
  'Akola': { state: 'Maharashtra', market: 'Akola' },
  'Amravati': { state: 'Maharashtra', market: 'Amravati' },
  'Aurangabad': { state: 'Maharashtra', market: 'Aurangabad' },
  'Beed': { state: 'Maharashtra', market: 'Aurangabad' },
  'Bhandara': { state: 'Maharashtra', market: 'Nagpur' },
  'Buldhana': { state: 'Maharashtra', market: 'Buldhana' },
  'Chandrapur': { state: 'Maharashtra', market: 'Nagpur' },
  'Dhule': { state: 'Maharashtra', market: 'Nashik' },
  'Gadchiroli': { state: 'Maharashtra', market: 'Nagpur' },
  'Gondia': { state: 'Maharashtra', market: 'Nagpur' },
  'Hingoli': { state: 'Maharashtra', market: 'Aurangabad' },
  'Jalgaon': { state: 'Maharashtra', market: 'Jalgaon' },
  'Jalna': { state: 'Maharashtra', market: 'Aurangabad' },
  'Kolhapur': { state: 'Maharashtra', market: 'Pune' },
  'Latur': { state: 'Maharashtra', market: 'Latur' },
  'Mumbai City': { state: 'Maharashtra', market: 'Mumbai' },
  'Mumbai Suburban': { state: 'Maharashtra', market: 'Mumbai' },
  'Nagpur': { state: 'Maharashtra', market: 'Nagpur' },
  'Nanded': { state: 'Maharashtra', market: 'Aurangabad' },
  'Nandurbar': { state: 'Maharashtra', market: 'Nashik' },
  'Nashik': { state: 'Maharashtra', market: 'Nashik' },
  'Osmana bad': { state: 'Maharashtra', market: 'Aurangabad' },
  'Palghar': { state: 'Maharashtra', market: 'Mumbai' },
  'Parbhani': { state: 'Maharashtra', market: 'Aurangabad' },
  'Pune': { state: 'Maharashtra', market: 'Pune' },
  'Raigad': { state: 'Maharashtra', market: 'Pune' },
  'Ratnagiri': { state: 'Maharashtra', market: 'Pune' },
  'Sangli': { state: 'Maharashtra', market: 'Pune' },
  'Satara': { state: 'Maharashtra', market: 'Pune' },
  'Sindhudurg': { state: 'Maharashtra', market: 'Pune' },
  'Solapur': { state: 'Maharashtra', market: 'Solapur' },
  'Thane': { state: 'Maharashtra', market: 'Mumbai' },
  'Wardha': { state: 'Maharashtra', market: 'Nagpur' },
  'Washim': { state: 'Maharashtra', market: 'Akola' },
  'Yavatmal': { state: 'Maharashtra', market: 'Akola' },

  // Manipur
  'Bishnupur': { state: 'Manipur', market: 'Imphal' },
  'Chandel': { state: 'Manipur', market: 'Imphal' },
  'Churachandpur': { state: 'Manipur', market: 'Imphal' },
  'Imphal East': { state: 'Manipur', market: 'Imphal' },
  'Imphal West': { state: 'Manipur', market: 'Imphal' },
  'Jiribam': { state: 'Manipur', market: 'Imphal' },
  'Kakching': { state: 'Manipur', market: 'Imphal' },
  'Kamjong': { state: 'Manipur', market: 'Imphal' },
  'Kangpokpi': { state: 'Manipur', market: 'Imphal' },
  'Noney': { state: 'Manipur', market: 'Imphal' },
  'Pherzawl': { state: 'Manipur', market: 'Imphal' },
  'Senapati': { state: 'Manipur', market: 'Imphal' },
  'Tamenglong': { state: 'Manipur', market: 'Imphal' },
  'Tengnoupal': { state: 'Manipur', market: 'Imphal' },
  'Thoubal': { state: 'Manipur', market: 'Imphal' },
  'Ukhrul': { state: 'Manipur', market: 'Imphal' },

  // Meghalaya
  'East Garo Hills': { state: 'Meghalaya', market: 'Shillong' },
  'East Jaintia Hills': { state: 'Meghalaya', market: 'Shillong' },
  'East Khasi Hills': { state: 'Meghalaya', market: 'Shillong' },
  'North Garo Hills': { state: 'Meghalaya', market: 'Shillong' },
  'Ri Bhoi': { state: 'Meghalaya', market: 'Shillong' },
  'South Garo Hills': { state: 'Meghalaya', market: 'Shillong' },
  'South West Garo Hills': { state: 'Meghalaya', market: 'Shillong' },
  'West Garo Hills': { state: 'Meghalaya', market: 'Shillong' },
  'West Jaintia Hills': { state: 'Meghalaya', market: 'Shillong' },
  'West Khasi Hills': { state: 'Meghalaya', market: 'Shillong' },

  // Mizoram
  'Aizawl': { state: 'Mizoram', market: 'Aizawl' },
  'Champhai': { state: 'Mizoram', market: 'Aizawl' },
  'Kolasib': { state: 'Mizoram', market: 'Aizawl' },
  'Lawngtlai': { state: 'Mizoram', market: 'Aizawl' },
  'Lunglei': { state: 'Mizoram', market: 'Aizawl' },
  'Mamit': { state: 'Mizoram', market: 'Aizawl' },
  'Saiha': { state: 'Mizoram', market: 'Aizawl' },
  'Serchhip': { state: 'Mizoram', market: 'Aizawl' },

  // Nagaland
  'Dimapur': { state: 'Nagaland', market: 'Dimapur' },
  'Kiphire': { state: 'Nagaland', market: 'Kohima' },
  'Kohima': { state: 'Nagaland', market: 'Kohima' },
  'Longleng': { state: 'Nagaland', market: 'Kohima' },
  'Mokokchung': { state: 'Nagaland', market: 'Mokokchung' },
  'Mon': { state: 'Nagaland', market: 'Kohima' },
  'Peren': { state: 'Nagaland', market: 'Kohima' },
  'Phek': { state: 'Nagaland', market: 'Kohima' },
  'Tuensang': { state: 'Nagaland', market: 'Kohima' },
  'Wokha': { state: 'Nagaland', market: 'Kohima' },
  'Zunheboto': { state: 'Nagaland', market: 'Kohima' },

  // Odisha
  'Angul': { state: 'Odisha', market: 'Rourkela' },
  'Balangir': { state: 'Odisha', market: 'Balangir' },
  'Balasore': { state: 'Odisha', market: 'Balasore' },
  'Bargarh': { state: 'Odisha', market: 'Rourkela' },
  'Bhadrak': { state: 'Odisha', market: 'Bhubaneswar' },
  'Boudh': { state: 'Odisha', market: 'Bhubaneswar' },
  'Cuttack': { state: 'Odisha', market: 'Cuttack' },
  'Deogarh': { state: 'Odisha', market: 'Rourkela' },
  'Dhenkanal': { state: 'Odisha', market: 'Bhubaneswar' },
  'Gajapati': { state: 'Odisha', market: 'Berhampur' },
  'Ganjam': { state: 'Odisha', market: 'Berhampur' },
  'Jagatsinghpur': { state: 'Odisha', market: 'Cuttack' },
  'Jajpur': { state: 'Odisha', market: 'Cuttack' },
  'Jharsuguda': { state: 'Odisha', market: 'Rourkela' },
  'Kalahandi': { state: 'Odisha', market: 'Balangir' },
  'Kandhamal': { state: 'Odisha', market: 'Berhampur' },
  'Kendrapara': { state: 'Odisha', market: 'Cuttack' },
  'Kendujhar': { state: 'Odisha', market: 'Rourkela' },
  'Khordha': { state: 'Odisha', market: 'Bhubaneswar' },
  'Koraput': { state: 'Odisha', market: 'Koraput' },
  'Malkangiri': { state: 'Odisha', market: 'Koraput' },
  'Mayurbhanj': { state: 'Odisha', market: 'Rourkela' },
  'Nabarangpur': { state: 'Odisha', market: 'Koraput' },
  'Nayagarh': { state: 'Odisha', market: 'Bhubaneswar' },
  'Nuapada': { state: 'Odisha', market: 'Balangir' },
  'Puri': { state: 'Odisha', market: 'Bhubaneswar' },
  'Rayagada': { state: 'Odisha', market: 'Berhampur' },
  'Sambalpur': { state: 'Odisha', market: 'Sambalpur' },
  'Subarnapur': { state: 'Odisha', market: 'Sambalpur' },
  'Sundargarh': { state: 'Odisha', market: 'Rourkela' },

  // Punjab
  'Amritsar': { state: 'Punjab', market: 'Amritsar' },
  'Barnala': { state: 'Punjab', market: 'Barnala' },
  'Bathinda': { state: 'Punjab', market: 'Bathinda' },
  'Faridkot': { state: 'Punjab', market: 'Faridkot' },
  'Fatehgarh Sahib': { state: 'Punjab', market: 'Chandigarh' },
  'Fazilka': { state: 'Punjab', market: 'Bathinda' },
  'Gurdaspur': { state: 'Punjab', market: 'Amritsar' },
  'Hoshiarpur': { state: 'Punjab', market: 'Hoshiarpur' },
  'Jalandhar': { state: 'Punjab', market: 'Jalandhar' },
  'Kapurthala': { state: 'Punjab', market: 'Jalandhar' },
  'Ludhiana': { state: 'Punjab', market: 'Ludhiana' },
  'Mansa': { state: 'Punjab', market: 'Barnala' },
  'Moga': { state: 'Punjab', market: 'Ludhiana' },
  'Muktsar': { state: 'Punjab', market: 'Bathinda' },
  'Nawanshahr': { state: 'Punjab', market: 'Jalandhar' },
  'Pathankot': { state: 'Punjab', market: 'Amritsar' },
  'Patiala': { state: 'Punjab', market: 'Patiala' },
  'Rupnagar': { state: 'Punjab', market: 'Chandigarh' },
  'Sangrur': { state: 'Punjab', market: 'Patiala' },
  'Shaheed Bhagat Singh Nagar': { state: 'Punjab', market: 'Jalandhar' },
  'Tarn Taran': { state: 'Punjab', market: 'Amritsar' },

  // Puducherry
  'Karaikal': { state: 'Puducherry', market: 'Pondicherry' },
  'Mahe': { state: 'Puducherry', market: 'Pondicherry' },
  'Puducherry': { state: 'Puducherry', market: 'Pondicherry' },
  'Yanam': { state: 'Puducherry', market: 'Pondicherry' },

  // Rajasthan
  'Ajmer': { state: 'Rajasthan', market: 'Ajmer' },
  'Alwar': { state: 'Rajasthan', market: 'Alwar' },
  'Banswara': { state: 'Rajasthan', market: 'Udaipur' },
  'Baran': { state: 'Rajasthan', market: 'Kota' },
  'Barmer': { state: 'Rajasthan', market: 'Jaisalmer' },
  'Bharatpur': { state: 'Rajasthan', market: 'Bharatpur' },
  'Bhilwara': { state: 'Rajasthan', market: 'Bhilwara' },
  'Bikaner': { state: 'Rajasthan', market: 'Bikaner' },
  'Bundi': { state: 'Rajasthan', market: 'Kota' },
  'Chittorgarh': { state: 'Rajasthan', market: 'Udaipur' },
  'Churu': { state: 'Rajasthan', market: 'Bikaner' },
  'Dausa': { state: 'Rajasthan', market: 'Jaipur' },
  'Dholpur': { state: 'Rajasthan', market: 'Agra' },
  'Dungarpur': { state: 'Rajasthan', market: 'Udaipur' },
  'Hanumangarh': { state: 'Rajasthan', market: 'Bikaner' },
  'Jaipur': { state: 'Rajasthan', market: 'Jaipur' },
  'Jaisalmer': { state: 'Rajasthan', market: 'Jaisalmer' },
  'Jalore': { state: 'Rajasthan', market: 'Jodhpur' },
  'Jhalawar': { state: 'Rajasthan', market: 'Kota' },
  'Jhunjhunu': { state: 'Rajasthan', market: 'Jaipur' },
  'Jodhpur': { state: 'Rajasthan', market: 'Jodhpur' },
  'Karauli': { state: 'Rajasthan', market: 'Agra' },
  'Kota': { state: 'Rajasthan', market: 'Kota' },
  'Nagaur': { state: 'Rajasthan', market: 'Jodhpur' },
  'Pali': { state: 'Rajasthan', market: 'Jodhpur' },
  'Pratapgarh': { state: 'Rajasthan', market: 'Udaipur' },
  'Rajsamand': { state: 'Rajasthan', market: 'Udaipur' },
  'Sawai Madhopur': { state: 'Rajasthan', market: 'Jaipur' },
  'Sikar': { state: 'Rajasthan', market: 'Jaipur' },
  'Sirohi': { state: 'Rajasthan', market: 'Jodhpur' },
  'Sri Ganganagar': { state: 'Rajasthan', market: 'Bikaner' },
  'Tonk': { state: 'Rajasthan', market: 'Jaipur' },
  'Udaipur': { state: 'Rajasthan', market: 'Udaipur' },

  // Sikkim
  'East Sikkim': { state: 'Sikkim', market: 'Gangtok' },
  'North Sikkim': { state: 'Sikkim', market: 'Gangtok' },
  'South Sikkim': { state: 'Sikkim', market: 'Gangtok' },
  'West Sikkim': { state: 'Sikkim', market: 'Gangtok' },

  // Tamil Nadu
  'Ariyalur': { state: 'Tamil Nadu', market: 'Cuddalore' },
  'Chengalpattu': { state: 'Tamil Nadu', market: 'Chennai' },
  'Chennai': { state: 'Tamil Nadu', market: 'Chennai' },
  'Coimbatore': { state: 'Tamil Nadu', market: 'Coimbatore' },
  'Cuddalore': { state: 'Tamil Nadu', market: 'Cuddalore' },
  'Dharmapuri': { state: 'Tamil Nadu', market: 'Dharmapuri' },
  'Dindigul': { state: 'Tamil Nadu', market: 'Dindigul' },
  'Erode': { state: 'Tamil Nadu', market: 'Erode' },
  'Kallakurichi': { state: 'Tamil Nadu', market: 'Villupuram' },
  'Kancheepuram': { state: 'Tamil Nadu', market: 'Chennai' },
  'Karur': { state: 'Tamil Nadu', market: 'Karur' },
  'Krishnagiri': { state: 'Tamil Nadu', market: 'Krishnagiri' },
  'Madurai': { state: 'Tamil Nadu', market: 'Madurai' },
  'Mayiladuthurai': { state: 'Tamil Nadu', market: 'Cuddalore' },
  'Nagapattinam': { state: 'Tamil Nadu', market: 'Thanjavur' },
  'Namakkal': { state: 'Tamil Nadu', market: 'Salem' },
  'Perambalur': { state: 'Tamil Nadu', market: 'Cuddalore' },
  'Pudukkottai': { state: 'Tamil Nadu', market: 'Madurai' },
  'Ramanathapuram': { state: 'Tamil Nadu', market: 'Ramanathapuram' },
  'Ranipet': { state: 'Tamil Nadu', market: 'Krishnagiri' },
  'Salem': { state: 'Tamil Nadu', market: 'Salem' },
  'Sivaganga': { state: 'Tamil Nadu', market: 'Madurai' },
  'Tenkasi': { state: 'Tamil Nadu', market: 'Tirunelveli' },
  'Thanjavur': { state: 'Tamil Nadu', market: 'Thanjavur' },
  'Theni': { state: 'Tamil Nadu', market: 'Madurai' },
  'Thoothukudi': { state: 'Tamil Nadu', market: 'Thoothukudi' },
  'Tiruchirappalli': { state: 'Tamil Nadu', market: 'Tiruchirappalli' },
  'Tirunelveli': { state: 'Tamil Nadu', market: 'Tirunelveli' },
  'Tirupathur': { state: 'Tamil Nadu', market: 'Krishnagiri' },
  'Tiruppur': { state: 'Tamil Nadu', market: 'Coimbatore' },
  'Tiruvallur': { state: 'Tamil Nadu', market: 'Chennai' },
  'Tiruvannamalai': { state: 'Tamil Nadu', market: 'Villupuram' },
  'Vellore': { state: 'Tamil Nadu', market: 'Vellore' },
  'Viluppuram': { state: 'Tamil Nadu', market: 'Villupuram' },
  'Virudhunagar': { state: 'Tamil Nadu', market: 'Virudunagar' },
  'Nilgiris': { state: 'Tamil Nadu', market: 'Coimbatore' },

  // Telangana
  'Adilabad': { state: 'Telangana', market: 'Hyderabad' },
  'Bhadradri Kothagudem': { state: 'Telangana', market: 'Hyderabad' },
  'Hyderabad': { state: 'Telangana', market: 'Hyderabad' },
  'Jagtial': { state: 'Telangana', market: 'Hyderabad' },
  'Jangaon': { state: 'Telangana', market: 'Hyderabad' },
  'Jayashankar Bhupalpally': { state: 'Telangana', market: 'Hyderabad' },
  'Jogulamba Gadwal': { state: 'Telangana', market: 'Hyderabad' },
  'Kamareddy': { state: 'Telangana', market: 'Hyderabad' },
  'Karimnagar': { state: 'Telangana', market: 'Karimnagar' },
  'Khammam': { state: 'Telangana', market: 'Khammam' },
  'Komaram Bheem Asifabad': { state: 'Telangana', market: 'Hyderabad' },
  'Mahabubabad': { state: 'Telangana', market: 'Hyderabad' },
  'Mahabubnagar': { state: 'Telangana', market: 'Hyderabad' },
  'Mancherial': { state: 'Telangana', market: 'Hyderabad' },
  'Medak': { state: 'Telangana', market: 'Hyderabad' },
  'Medchal Malkajgiri': { state: 'Telangana', market: 'Hyderabad' },
  'Mulugu': { state: 'Telangana', market: 'Hyderabad' },
  'Nagarkurnool': { state: 'Telangana', market: 'Hyderabad' },
  'Nalgonda': { state: 'Telangana', market: 'Hyderabad' },
  'Narayanpet': { state: 'Telangana', market: 'Hyderabad' },
  'Nirmal': { state: 'Telangana', market: 'Hyderabad' },
  'Nizamabad': { state: 'Telangana', market: 'Nizamabad' },
  'Peddapalli': { state: 'Telangana', market: 'Hyderabad' },
  'Rajanna Sircilla': { state: 'Telangana', market: 'Hyderabad' },
  'Rangareddy': { state: 'Telangana', market: 'Hyderabad' },
  'Sangareddy': { state: 'Telangana', market: 'Hyderabad' },
  'Siddipet': { state: 'Telangana', market: 'Hyderabad' },
  'Suryapet': { state: 'Telangana', market: 'Hyderabad' },
  'Vikarabad': { state: 'Telangana', market: 'Hyderabad' },
  'Wanaparthy': { state: 'Telangana', market: 'Hyderabad' },
  'Warangal (Rural)': { state: 'Telangana', market: 'Warangal' },
  'Warangal (Urban)': { state: 'Telangana', market: 'Warangal' },
  'Yadadri Bhuvanagiri': { state: 'Telangana', market: 'Hyderabad' },

  // Tripura
  'Dhalai': { state: 'Tripura', market: 'Agartala' },
  'Gomati': { state: 'Tripura', market: 'Agartala' },
  'Khowai': { state: 'Tripura', market: 'Agartala' },
  'North Tripura': { state: 'Tripura', market: 'Agartala' },
  'Sepahijala': { state: 'Tripura', market: 'Agartala' },
  'South Tripura': { state: 'Tripura', market: 'Agartala' },
  'Unakoti': { state: 'Tripura', market: 'Agartala' },
  'West Tripura': { state: 'Tripura', market: 'Agartala' },

  // Uttar Pradesh
  'Agra': { state: 'Uttar Pradesh', market: 'Agra' },
  'Aligarh': { state: 'Uttar Pradesh', market: 'Aligarh' },
  'Allahabad': { state: 'Uttar Pradesh', market: 'Prayagraj' },
  'Ambedkar Nagar': { state: 'Uttar Pradesh', market: 'Mandi' },
  'Amethi': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Amroha': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Auraiya': { state: 'Uttar Pradesh', market: 'Gwalior' },
  'Azamgarh': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Baghpat': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Bahraich': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Ballia': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Balrampur': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Banda': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Barabanki': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Bareilly': { state: 'Uttar Pradesh', market: 'Bareilly' },
  'Basti': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Bhadohi': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Bijnor': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Budaun': { state: 'Uttar Pradesh', market: 'Bareilly' },
  'Bulandshahr': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Chandauli': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Chitrakoot': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Deoria': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Etah': { state: 'Uttar Pradesh', market: 'Bareilly' },
  'Etawah': { state: 'Uttar Pradesh', market: 'Agra' },
  'Faizabad': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Farrukhabad': { state: 'Uttar Pradesh', market: 'Agra' },
  'Fatehpur': { state: 'Uttar Pradesh', market: 'Prayagraj' },
  'Firozabad': { state: 'Uttar Pradesh', market: 'Agra' },
  'Gautam Buddha Nagar': { state: 'Uttar Pradesh', market: 'Noida' },
  'Ghaziabad': { state: 'Uttar Pradesh', market: 'Delhi' },
  'Ghazipur': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Gonda': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Gorakhpur': { state: 'Uttar Pradesh', market: 'Gorakhpur' },
  'Hamirpur': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Hapur': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Hardoi': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Hathras': { state: 'Uttar Pradesh', market: 'Agra' },
  'Jalaun': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Jaunpur': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Jhansi': { state: 'Uttar Pradesh', market: 'Jhansi' },
  'Kannauj': { state: 'Uttar Pradesh', market: 'Agra' },
  'Kanpur Dehat': { state: 'Uttar Pradesh', market: 'Kanpur' },
  'Kanpur Nagar': { state: 'Uttar Pradesh', market: 'Kanpur' },
  'Kasganj': { state: 'Uttar Pradesh', market: 'Agra' },
  'Kaushambi': { state: 'Uttar Pradesh', market: 'Prayagraj' },
  'Kheri (Lakhimpur Kheri)': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Kushinagar': { state: 'Uttar Pradesh', market: 'Gorakhpur' },
  'Lucknow': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Maharajganj': { state: 'Uttar Pradesh', market: 'Gorakhpur' },
  'Mahoba': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Mainpuri': { state: 'Uttar Pradesh', market: 'Agra' },
  'Mathura': { state: 'Uttar Pradesh', market: 'Agra' },
  'Mau': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Meerut': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Mirzapur': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Moradabad': { state: 'Uttar Pradesh', market: 'Moradabad' },
  'Muzaffarnagar': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Pilibhit': { state: 'Uttar Pradesh', market: 'Bareilly' },
  'Pratapgarh': { state: 'Uttar Pradesh', market: 'Prayagraj' },
  'Rae Bareli': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Rampur': { state: 'Uttar Pradesh', market: 'Moradabad' },
  'Saharanpur': { state: 'Uttar Pradesh', market: 'Saharanpur' },
  'Sambhal': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Sant Kabir Nagar': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Shahjahanpur': { state: 'Uttar Pradesh', market: 'Bareilly' },
  'Shamli': { state: 'Uttar Pradesh', market: 'Meerut' },
  'Shravasti': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Siddharthnagar': { state: 'Uttar Pradesh', market: 'Gorakhpur' },
  'Sitapur': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Sonbhadra': { state: 'Uttar Pradesh', market: 'Varanasi' },
  'Sultanpur': { state: 'Uttar Pradesh', market: 'Lucknow' },
  'Unnao': { state: 'Uttar Pradesh', market: 'Lucknow' },

  // West Bengal
  'Alipurduar': { state: 'West Bengal', market: 'Siliguri' },
  'Bankura': { state: 'West Bengal', market: 'Kolkata' },
  'Birbhum': { state: 'West Bengal', market: 'Kolkata' },
  'Cooch Behar': { state: 'West Bengal', market: 'Siliguri' },
  'Dakshin Dinajpur': { state: 'West Bengal', market: 'Siliguri' },
  'Darjeeling': { state: 'West Bengal', market: 'Siliguri' },
  'East Burdwan': { state: 'West Bengal', market: 'Kolkata' },
  'Hooghly': { state: 'West Bengal', market: 'Kolkata' },
  'Howrah': { state: 'West Bengal', market: 'Kolkata' },
  'Jalpaiguri': { state: 'West Bengal', market: 'Siliguri' },
  'Jhargram': { state: 'West Bengal', market: 'Kolkata' },
  'Kalimpong': { state: 'West Bengal', market: 'Siliguri' },
  'Kolkata': { state: 'West Bengal', market: 'Kolkata' },
  'Maldah': { state: 'West Bengal', market: 'Malda' },
  'Medinipur': { state: 'West Bengal', market: 'Kolkata' },
  'Murshidabad': { state: 'West Bengal', market: 'Kolkata' },
  'Nadia': { state: 'West Bengal', market: 'Kolkata' },
  'North 24 Parganas': { state: 'West Bengal', market: 'Kolkata' },
  'Paschim Medinipur': { state: 'West Bengal', market: 'Kolkata' },
  'Purba Medinipur': { state: 'West Bengal', market: 'Kolkata' },
  'Purulia': { state: 'West Bengal', market: 'Kolkata' },
  'South 24 Parganas': { state: 'West Bengal', market: 'Kolkata' },
  'Uttar Dinajpur': { state: 'West Bengal', market: 'Siliguri' },
  'West Burdwan': { state: 'West Bengal', market: 'Kolkata' }
};


export const MarketPriceService = {
  
  // ✅ Get REAL-TIME prices from Agmarknet
  getRealTimePrices: async (district, commodity) => {
    try {
      const standardCommodity = CROP_MAPPING[commodity] || commodity;
      const marketInfo = DISTRICT_TO_MARKET[district];
      
      if (!marketInfo) {
        console.warn(`⚠️ Market not found for district: ${district}`);
        return MarketPriceService.getMockPrice(commodity); // Fallback
      }

      // Agmarknet API endpoint
      const url = `${AGMARKNET_BASE_URL}/market_price`;
      
      const response = await axios.get(url, {
        params: {
          commodities: standardCommodity,
          market: marketInfo.market,
          state: marketInfo.state,
          apitype: 'latest'
        },
        timeout: 8000
      });

      if (response.data && response.data.length > 0) {
        const priceData = response.data[0];
        
        return {
          commodity: commodity,
          minPrice: parseInt(priceData.min_price) || 0,
          maxPrice: parseInt(priceData.max_price) || 0,
          modalPrice: parseInt(priceData.modal_price) || 0,
          market: marketInfo.market,
          state: marketInfo.state,
          date: priceData.price_date || new Date().toISOString().split('T')[0],
          lastUpdated: new Date().toLocaleTimeString(),
          source: 'Agmarknet (Real-Time)',
          dataAvailable: true
        };
      }
      
      return MarketPriceService.getMockPrice(commodity);
      
    } catch (error) {
      console.error('❌ Agmarknet API error:', error.message);
      return MarketPriceService.getMockPrice(commodity); // Fallback to mock
    }
  },

  // ✅ Get price history (last 7 days)
  getPriceHistory: async (district, commodity) => {
    try {
      const standardCommodity = CROP_MAPPING[commodity] || commodity;
      const marketInfo = DISTRICT_TO_MARKET[district];
      
      if (!marketInfo) {
        return [];
      }

      const url = `${AGMARKNET_BASE_URL}/market_price`;
      
      const response = await axios.get(url, {
        params: {
          commodities: standardCommodity,
          market: marketInfo.market,
          state: marketInfo.state,
          apitype: 'lastsevendays'
        },
        timeout: 8000
      });

      if (response.data && Array.isArray(response.data)) {
        return response.data
          .slice(0, 7)
          .map(item => ({
            date: item.price_date,
            minPrice: parseInt(item.min_price),
            maxPrice: parseInt(item.max_price),
            modalPrice: parseInt(item.modal_price)
          }))
          .reverse(); // Latest first
      }
      
      return [];
      
    } catch (error) {
      console.error('❌ Price history error:', error.message);
      return [];
    }
  },

  // ✅ Fallback mock data
  getMockPrice: (commodity) => {
    const basePrices = {
      'Rice': 4500, 'Wheat': 2500, 'Maize': 2000, 'Potato': 1500,
      'Tomato': 3500, 'Onion': 2800, 'Cotton': 5500, 'Sugarcane': 3000,
      'Mango': 8000, 'Banana': 3500, 'Apple': 7000
    };

    const basePrice = basePrices[commodity] || 3000;
    const variance = basePrice * 0.15;

    return {
      commodity: commodity,
      minPrice: Math.round(basePrice - variance),
      maxPrice: Math.round(basePrice + variance),
      modalPrice: basePrice,
      market: 'Default Market',
      state: 'Default State',
      date: new Date().toISOString().split('T')[0],
      lastUpdated: new Date().toLocaleTimeString(),
      source: 'Mock Data (Agmarknet Unavailable)',
      dataAvailable: false
    };
  }
};