export const INDIAN_LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧', recommended: true, region: 'National' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳', recommended: false, region: 'North India' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳', recommended: false, region: 'Tamil Nadu' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳', recommended: false, region: 'Telangana, Andhra Pradesh' },
  { code: 'ka', name: 'ಕನ್ನಡ', flag: '🇮🇳', recommended: false, region: 'Karnataka' },
  { code: 'ml', name: 'മലയാളം', flag: '🇮🇳', recommended: false, region: 'Kerala' },
  { code: 'mr', name: 'मराठी', flag: '🇮🇳', recommended: false, region: 'Maharashtra' },
  { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳', recommended: false, region: 'Gujarat' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳', recommended: false, region: 'Punjab' },
  { code: 'bn', name: 'বাংলা', flag: '🇮🇳', recommended: false, region: 'West Bengal, Assam' },
  { code: 'ur', name: 'اردو', flag: '🇮🇳', recommended: false, region: 'Northern regions' },
  { code: 'or', name: 'ଓଡ଼ିଆ', flag: '🇮🇳', recommended: false, region: 'Odisha' },
];

export const INDIAN_STATES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Jammu and Kashmir',
  'Karnataka',
  'Kerala',
  'Ladakh',
  'Lakshadweep',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Puducherry',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal'
];

